### ISSUE TITLE
Change state programmatically

### ISSUE THREAD

**Issue by Lulli4444** [plavatvornica/CustomUISwitch#1]
Hi,
how can I change the state programmatically? If I set the property isOn, only when the view is draw again it will show the change.

**Comment by aatanac** [comment]
Hi,
Thank you for having noticed this kind of behavior. It was fixed with last commit https://github.com/plavatvornica/CustomUISwitch/commit/57536efc99cc9d1972c2aca40c3a48e61fafc77c .
